### ISSUE TITLE
byte array length 

### ISSUE THREAD

**Issue by markraylee** [andyleap/gencode#10]
There seems to be an issue with byte arrays

do something like this -- ( the real code is in a big app ) -- i can create a better example if needed

seudo code...

struct Info  {
	Raw      []byte
}

is1 := &Info{}
is1.Raw = []byte("testbytearray")
raw1, _ := is1.Marshal(nil)
ig1 := &Info{}
ig1.Unmarshal(raw1)

fmt.Printf("Test1 1 %s %s", string(is1.Raw), string(ig1.Raw))
fmt.Printf("Test1 2 %v %v", is1.Raw, ig1.Raw)
fmt.Printf("Test1 3  %s %s", global.ToJSONPretty(is1), global.ToJSONPretty(ig1))

 Test1 -- print as string works
 testbytearray
 testbytearray   

Test2 -- print as %v
  [116 101 115 116 98 121 116 101 97 114 114 97 121] 
[116 101 115 116 98 121 116 101 97 114 114 97 121 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Test3 -- Convert struct to json print

"Raw": "dGVzdGJ5dGVhcnJheQ=="
"Raw": "dGVzdGJ5dGVhcnJheQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

if the byte array is large and mixed in a bigger struct i get a panic  ( the real use case)

**Comment by andyleap** [comment]
I didn't do the json bit, but my almost exact copy of this prints out

    Test1 1 testbytearray testbytearray
    Test1 2 [116 101 115 116 98 121 116 101 97 114 114 97 121] [116 101 115 116 98 121 116 101 97 114 114 97 121]

It might help if you can send the generated `.schema.gen.go` file

**Comment by markraylee** [comment]
they the basic one worked for me also -- here is close to what we are actually doing
NOTE: I do a few mods to your coded to pass lint i forked the code
https://github.com/markraylee/gencode
SO this may be totally my bad....

--schema

struct InfoImpressionInfo  {
	URL string
}

struct InfoErrorInfo  {
	URL string
}

struct InfoTrackingInfo  {
	Event string
	URL   string
}

struct InfoAd  {
	ID          string
	AdBreakName  string
	Impressions []*InfoImpressionInfo
	Errors      []*InfoErrorInfo
	Tracking    []*InfoTrackingInfo
	SourceFile  string
	ThirdParty   bool
	Raw      []byte
}

struct Info  {
	Personalized bool
	Smart        bool
	Ads          []*InfoAd
}

-- code

package main

import "fmt"

func CreateInfo() *Info {
	vi := &Info{}
	vi.Smart = true

	ad1 := &InfoAd{}
	ad1.Raw = []byte("testbytearray")
	ad1.ID = "ad1"
	vi.Ads = append(vi.Ads, ad1)
	return vi
}

func main() {
	is1 := CreateInfo()
	raw1, _ := is1.Marshal(nil)
	ig1 := &Info{}
	ig1.Unmarshal(raw1)
	fmt.Printf("Test1 1 \n %s\n %s\n", string(is1.Ads[0].Raw), string(ig1.Ads[0].Raw))
	fmt.Printf("Test1 2 \n %v\n %v\n", is1.Ads[0].Raw, ig1.Ads[0].Raw)
	//fmt.Printf("Test1 3  %s %s", global.ToJSONPretty(vis1), global.ToJSONPretty(vig1))
}

--output

marklee@marklee-MBPR15 genexample $ ./bin/bytearr
Test1 1
 testbytearray
 testbytearray
Test1 2
 [116 101 115 116 98 121 116 101 97 114 114 97 121]
 [116 101 115 116 98 121 116 101 97 114 114 97 121 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

**Comment by markraylee** [comment]
Also fails ---

struct InfoAd  {
	ID          string
	ThirdParty   bool
	Raw      []byte
}

struct Info  {
	Smart bool
	Ads          []*InfoAd
}


Works--

struct InfoAd  {
	ID          string
	Raw      []byte
}

struct Info  {
	Smart bool
	Ads          []*InfoAd
}

**Comment by andyleap** [comment]
Ok, that was useful.  Just pushed a fix that should take care of it.

**Comment by markraylee** [comment]
Works Now!!  Thanks for the quick fix.

**Comment by andyleap** [comment]
No problem.  I'm gonna go ahead and close this. (p.s. if you are working on something opensource, drop me a link, I'd love to add "projects that use gencode" to the readme, cause generated code tends not to leave a "trail" back here)
