### ISSUE TITLE
How to parse a json array()

### ISSUE THREAD

**Issue by petric3** [andyleap/gencode#28]
I am migrating from python to golang, and am struggling quite a lot. I have a problem something like this with GBs of lines (speed very important) each containing json array:
```
------ file xy.log with lots of lines-------
[{"str1":"hello","value1":1.2,"value2":3.14,"time":12345678912},{"str1":"world","value1":2.1,"value2":4.43,"time":12345678913}]
[{"str1":"hello","value1":1.2,"value2":3.14,"time":12345678912},{"str1":"world","value1":2.1,"value2":4.43,"time":12345678913},{"str1":"dinner","value1":12.1,"value2":24.43,"time":12345678914}]
[{"str1":"hello","value1":1.2,"value2":3.14,"time":12345678912},{"str1":"world","value1":2.1,"value2":4.43,"time":12345678913}]

```
I wonder if it is possible to iterate via lines and parse the json array? Any help very much appreciated.

**Comment by andyleap** [comment]
This is a library for a custom encoding generation system, not anything for json.  I'd suggest reading the docs for encoding/json or looking at alternative json libraries for Go.
