### ISSUE TITLE
Unsafe option generates faulty code

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [andyleap/gencode#5]
Please find attached the schema for a struct and the corresponding _.go_ files generated with the following commands: `gencode go -schema user.schema -package datatypes` and `gencode go -schema user.schema -package datatypes -unsafe`.

The Marshal method in the _unsafe_ file sets the three `int64` fields to zero (see lines 214-224):

`	{

		d.LastSeen = *(*int64)(unsafe.Pointer(&buf[i+0]))

	}
	{

		d.Created = *(*int64)(unsafe.Pointer(&buf[i+8]))

	}
	{

		d.Updated = *(*int64)(unsafe.Pointer(&buf[i+16]))

	}
	return buf[:i+24], nil
`

Using `time` fields (still undocumented?) instead of `int64` works fine.

[issue.zip](https://github.com/andyleap/gencode/files/224435/issue.zip)

**Comment by alessandrousseglioviretta** [comment]
it seems that line 45 in _type_int.go_ is the culprit:

`{{.Target}} = *(*{{if not .Signed}}u{{end}}int{{.Bits}})(unsafe.Pointer(&buf[{{if $.W.IAdjusted}}i + {{end}}{{$.W.Offset}}]))`

it shouldn't set the _.Target_ but fill the _buf_

**Comment by andyleap** [comment]
Yeah, I'll take care of that when I get home in a few hours
