### ISSUE TITLE
Not Working for me

### ISSUE THREAD

**Issue by ohenepee** [andyleap/gencode#6]
I'm new to this whole code-generated data serialization thingy... and I hope I followed the correct steps

1. my main() code, named `gencoder.go`
```
package main

import "fmt"

func main() {
	entry := Datadoc{
		ID: "45678911452457710", 
		Name: "Test Item", 
		Desc: "This is a test description. Length isn't really a matter here", 
		Numb: 8, 
		AnArray: []string{"as54dasd897asd","as5d456a4sd4756","as8d7as987da7sd8f"}, 
	}
	buf, _ := entry.Marshal(nil)
	fmt.Printf("Gencode'd size: %v\n", len(buf))
	fmt.Printf("Gencode'd data: %s\n", buf)
}
```

2. my schema, named `new.schema`
```
struct Datadoc {
	ID string
	Name string
	Desc string
	Numb int32
	AnArray []string
}
```

3. I run the command `gencode go -schema new.schema -package main` and I see the newly generated file named `new.schema.gen.go` in the same folder as the `new.schema` and `gencoder.go`

Now when I do `go run gencoder.go` in my working directory, I get the following error:
```
# command-line-arguments
.\gencoder.go:13: entry.Marshal undefined (type Datadoc has no field or method Marshal)
```

Anything I'm missing? BTW: I'm using Windows XP Pro SP3

**Comment by andyleap** [comment]
The problem is that `go run file.go` only compiles and runs that single file.  The code for the `.Marshal()` method is in the `new.schema.gen.go` file, so it'd not getting compiled in.  You could do something like `go run *.go`, but you'll probably be better off going with the more normal practice of `go build` followed by running the built binary.

**Comment by ohenepee** [comment]
`go build gencoder.go` also produces a similar error
```
# command-line-arguments
.\gencoder.go:6: undefined: Datadoc
```

**Comment by andyleap** [comment]
No, this is a lack of experience with Go itself.  I would recommend reading the documentation, as you seem to be struggling with the basics.  Just for reference, I copied your files, and then ran `gencode go -schema new.schema` and `go build`, followed by running the resulting binary, and got
```
Gencode'd size: 144
Gencode'd data: ◄45678911452457710      Test Item=This is a test description. Length isn't really a matter her   ♥♫as54dasd897asd☼as5d456a4sd4756◄as8d7as987da7s
d8f
```

**Comment by ohenepee** [comment]
Yep! It does work... thanks anyway
