### ISSUE TITLE
Slice of struct pointers

### ISSUE THREAD

**Issue by markraylee** [andyleap/gencode#7]
struct Rider {
	Name string
}

struct Car  {
	Name      string
	Riders    []*Rider
}

serial $ gencode go -schema car.schema -package car
2016/05/24 21:09:05 Error generating output: template: marshal:4:39: executing "marshal" at <.Offset>: Offset is not a field of struct type golang.PointerTemp

Can i do this ? If i remove the pointer "*" it works

**Comment by andyleap** [comment]
Should be fixed now :)

**Comment by markraylee** [comment]
Thanks!!  fyi cool little app

**Comment by andyleap** [comment]
Lol, Thanks, it's always nice to see people messing with it :).
