### ISSUE TITLE
Feature Request: Gods containers

### ISSUE THREAD

**Issue by 5k3105** [andyleap/gencode#9]
I use the generic container library [https://github.com/emirpasic/gods] quite frequently instead of go maps and slices. Would it be incredibly difficult to add a backend for these types?

**Comment by andyleap** [comment]
I'm not opposed to this, but I don't want to implement it for those just those types.  If you are talking just replacing []T (gencode currently doesn't have maps) with a GODS equiv, that should be feasible by copying and reworking the Go backend a little.  I'd be willing to look at merging in changes if you feel like making them, but it'll probably be a while before I can get around to it.
